name: habesha
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  awesome_notifications: ^0.0.6+10
  flutter_spinkit: ^5.2.0
  google_maps_flutter: ^2.2.8
  abushakir: ^1.0.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  intl: any
  flutter_staggered_grid_view: ^0.4.0
  google_sign_in: ^6.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_riverpod: ^2.3.6

  syncfusion_flutter_calendar: ^21.2.3
  card_swiper: ^2.0.4
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_charts: ^21.2.10
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner:
  hive_generator:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/hab.png"
  flutter_lints: ^2.0.0

flutter:
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/person/
    - assets/historical/

  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
